# Generated by Django 3.1.3 on 2020-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Check', '0002_card_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
