# Generated by Django 3.1.3 on 2020-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Check', '0003_auto_20201219_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, null=True, unique=True, verbose_name='Task')),
            ],
        ),
    ]
